---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_cpu
no_index:
  directory:
    - inc
requires:
  Carp: 0
  English: 0
  File::Copy: 0
  File::Temp: 0
  Getopt::Long: 0
  Nagios::Plugin: 0
  Nagios::Plugin::Threshold: 0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.1.0
